function result = predictFunction(varargin)
%#function fitctree
% result = predictFunction(varargin)   returns prediction results using the model trained in Classification Learner R2021b
%
%  Input:
%      varargin: Input argument must be a matrix, whose 999 columns have the same order as the predictor variables that trained the deployed model.
%  Output:
%      result: Prediction results returned by the trained, deployed model

% Auto-generated by MATLAB on 14-Dec-2021 13:39:04

inputData = varargin{1};
if ismatrix(inputData) && size(inputData,2) == 999
    T = inputData;

    % Uncomment the following lines of code if you used preprocessing
    % steps before importing data into Classification Learner. Add the
    % preprocessing steps to the processInputData.m file in the
    % SVMBad_resources folder.

    % processedData = processInputData(T);
    % T = processedData;

else
    error('stats:mlearnapp:DeployedModelError', 'Input argument must be a 999-column matrix.');
end

fileData = load('TrainedClassificationModel.mat');
model = fileData.trainedModel;
result = model.predictFcn(T);

end

